// Example: auth-service/Jenkinsfile
pipeline {
    agent any
    environment {
        AWS_REGION = 'eu-west-1'
        ECR_URI = '395338916491.dkr.ecr.eu-west-1.amazonaws.com'
        SERVICE_NAME = 'auth-service'
        IMAGE_TAG = 'latest'
        CLUSTER_NAME = 'whatsthecraic-cluster'
        TASK_DEF_FILE = 'auth-service/auth-task-definition.json'
        TASK_DEF_NAME = 'auth-task'
    }
     stages {

        stage('Build') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh "docker build -t whatsthecraic/${SERVICE_NAME} ."
                }
            }
        }
        stage('Push to ECR') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh """
                        docker tag ${SERVICE_NAME}:${IMAGE_TAG} ${ECR_URI}/${SERVICE_NAME}:${IMAGE_TAG}
                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}
                        docker push ${ECR_URI}/${SERVICE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }
        stage('Register Task Def') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh "aws ecs register-task-definition --cli-input-json file://${TASK_DEF_FILE} --region ${AWS_REGION}"
                }
            }
        }
        stage('Update ECS Service') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                    sh "aws ecs update-service --cluster ${CLUSTER_NAME} --service ${SERVICE_NAME} --task-definition ${TASK_DEF_NAME} --region ${AWS_REGION}"
                }
            }
        }
    }
}

