// Example: events-service/Jenkinsfile
pipeline {
    agent any
    environment {
        AWS_REGION = 'eu-west-1'
        ECR_URI = '395338916491.dkr.ecr.eu-west-1.amazonaws.com'
        SERVICE_NAME = 'events-service'
        IMAGE_TAG = 'latest'
        CLUSTER_NAME = 'whatsthecraic-cluster'
        TASK_DEF_FILE = 'events-service/events-task-definition.json'
        TASK_DEF_NAME = 'events-task'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/UT07/whatsthecraic.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh "docker build -t whatsthecraic/${SERVICE_NAME} ."
                }
            }
        }
        stage('Push to ECR') {
            steps {
                sh "docker tag whatsthecraic/${SERVICE_NAME}:${IMAGE_TAG} ${ECR_URI}/whatsthecraic/${SERVICE_NAME}:${IMAGE_TAG}"
                sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}"
                sh "docker push ${ECR_URI}/whatsthecraic/${SERVICE_NAME}:${IMAGE_TAG}"
            }
        }
        stage('Register Task Definition') {
            steps {
                sh "aws ecs register-task-definition --cli-input-json file://${TASK_DEF_FILE} --region ${AWS_REGION}"
            }
        }
        stage('Update ECS Service') {
            steps {
                sh "aws ecs update-service --cluster ${CLUSTER_NAME} --service ${SERVICE_NAME} --task-definition ${TASK_DEF_NAME} --region ${AWS_REGION}"
            }
        }
    }
}
